### PR TITLE
New CMake build system using CMake v2.8.12.2+ conventions

### PR DESCRIPTION
**Pull request by kmpaul**
This merge changes the layout of the source directories and introduces a new build system using CMake 2.8.12.2+ conventions (granular control over compiler flags, pre-processor macros, link libraries, etc for each target).

In general, on whatever system you are building, you should be able to configure with the following CMake variables defined on the cmake command line:

REQUIRED:
NetCDF_PATH
PnetCDF_PATH

OPTIONAL:
CMAKE_UTILS_PATH (i.e., where CMake_Fortran_utils is located)
GENF90_PATH

On some systems, you may need to also add:
HDF5_PATH
LIBZ_PATH

You may also specify PREFER_STATIC or PREFER_SHARED to indicate the preference for static/shared libraries when finding the main dependencies (NetCDF, PnetCDF, HDF5, LIBZ).  

If desired, I can add the cmake lines for the 3 systems I've been using for testing (Edison, Cetus, and Yellowstone).

### CODE REVIEW

**Comment by jedwards4b** [comment]
There is a lot of essential code in the unused directory.  prune_decomps.pl,
all of the *template* code and the ncparser*pl code.    That needs to be put back, but not necessarily in the source directory.   Lets talk Monday about how that code is used and the best way to integrate it with cmake and directory structure.

**Comment by kmpaul** [comment]
Jim,

Where do you want the prune_decomps.pl script to go?  I think it's fair to have a top-level "scripts" directory, which is how it existed before.  I can put that back in, and we can talk about what should go into this directory.  Then, I can add it to the CMake build system.  (I still need to add the examples directory to the CMake build, too.)

**Comment by jedwards4b** [comment]
I think that a top level scripts directory is fine and maybe it should also
include any scripts we need for the automated testing.

On Mon, Aug 24, 2015 at 9:57 AM, Kevin Paul <notifications@github.com>
wrote:

> Jim,
>
> Where do you want the prune_decomps.pl script to go? I think it's fair to
> have a top-level "scripts" directory, which is how it existed before. I can
> put that back in, and we can talk about what should go into this directory.
> Then, I can add it to the CMake build system. (I still need to add the
> examples directory to the CMake build, too.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PARALLELIO/ParallelIO/pull/3#issuecomment-134261575>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by kmpaul** [comment]
Yeah.  That works.  I'll do that, and if there are any scripts that are in
_UNUSED_/scripts/ (other than prun_decomps.pl) that you want moved into
this directory, just let me know.

On Mon, Aug 24, 2015 at 10:10 AM, jedwards4b <notifications@github.com>
wrote:

> I think that a top level scripts directory is fine and maybe it should also
> include any scripts we need for the automated testing.
>
> On Mon, Aug 24, 2015 at 9:57 AM, Kevin Paul <notifications@github.com>
> wrote:
>
> > Jim,
> >
> > Where do you want the prune_decomps.pl script to go? I think it's fair
> to
> > have a top-level "scripts" directory, which is how it existed before. I
> can
> > put that back in, and we can talk about what should go into this
> directory.
> > Then, I can add it to the CMake build system. (I still need to add the
> > examples directory to the CMake build, too.)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PARALLELIO/ParallelIO/pull/3#issuecomment-134261575
> >.
> >
>
>
>
> --
> Jim Edwards
>
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PARALLELIO/ParallelIO/pull/3#issuecomment-134271326>.
>



-- 
____________________________________________________________
Kevin Paul
The National Center for Atmospheric Research
Computational and Information Systems Laboratory
(303) 497-2441

**Pull request merged**
